scripts/data/actors/starwalker.lua

A very small pull request. This one fixes the broken sprite path in Starwalker's actor file, which caused the actor to be invisible on the map during gameplay.

Fixed the Starwalker actor to show sprite properly.

---

libraries/lighttransition/scripts/objects/LightTransition.lua
mod.lua

`Mod:getLeader()` takes one argument, a string, which can be:
- `"character"` or `"chara"`: returns the Character class
- `"sprite"` or `"actorsprite"`: returns the ActorSprite class
- `"actor"`: returns the Actor class
If the argument isn't one of them or nil, it'll return the PartyMember class

Replaced Mod:getKris() functions by Mod:getLeader()

---

libraries/Ultimate RIBBIT/scripts/hooks/LightSaveMenu.lua

Backwards compatibility moment

Prevent load fail due to LightSaveMenu being absent in older versions of Kristal

---

libraries/Ultimate RIBBIT/scripts/hooks/LightSaveMenu.lua
libraries/Ultimate RIBBIT/scripts/hooks/SaveMenu.lua
libraries/Ultimate RIBBIT/scripts/hooks/Savepoint.lua
libraries/Ultimate RIBBIT/scripts/hooks/SimpleSaveMenu.lua

Made the following changes:
- Interacting with save points no longer plays `power` on top of `powerfrog`
- `powerfrog` now correctly plays on save points without flavor text
- Changed the "File Saved" text to "There we go."
- The way I did this one sucks please find a better way to do it
All of these changes rely on the party leader being a Ribbit character, of course. If that's not the case, then none of these changes will actually do anything.

Save point/menu tweaks

---

scripts/hooks/Soul.lua
scripts/main/ow_taunt.lua

Downed party members will no longer taunt in battle, and you can no longer taunt when the console or debug menu is open.

Fix taunting at incorrect times

---

scripts/hooks/Player.lua
scripts/hooks/Soul.lua
scripts/main/ow_taunt.lua

No longer has to be worn by the party leader for taunting to be enabled. Did the same for the focus placebo once that's obtainable.

Made the PizzaToque work regardless of who's wearing it

---

scripts/battle/cutscenes/dummy.lua
scripts/battle/enemies/inf_dummy.lua
scripts/hooks/Battle.lua
scripts/hooks/Soul.lua
scripts/objects/ConcentrateBG.lua

- The outline now applies to whoever has Focus equipped. Also added the CONCENTRATING thing seen in RIBBIT.
- The infinite dummy Stop act now just sets the battle state to `TRANSITIONOUT` instead of running `battle:returnToWorld()`, which crashes at the moment in this setup.

Timeslow FX improvement + "Fix" inf dummy crash

---

mod.lua

YOU could not have the Magic button, Robo-Susie and Noyno couldn't have the ACT button, and _none_ of them could have the Skill button. All of this has been fixed.

Fix RIBBIT characters not getting the right action buttons

---

scripts/objects/world/WarpBinInputMenu.lua

Pass a number when creating the warp bin input to change the length. Defaults to 8 if no number is passed.

Variable length for Warp Bin Input

---

libraries/elevators/scripts/world/events/elevator.lua
libraries/elevators/scripts/world/events/elevatorbuttons.lua
scripts/world/maps/elevator.lua
scripts/world/maps/elevator.tmx

The direction the elevator will move when moving floors is now dependent on which floor you're currently on. this removes the need for `dir` properties in the elevator event, but if one is defined, it'll still use that.

Elevator movement fix

---

scripts/hooks/Battle.lua

set `self.refundable = false` in the item script to disable getting money back from refund.

allow items to opt out of refund

---

scripts/objects/minigame/BallJump/BallJump.lua

Button prompts in Ball Jump used to be replaced by something like `[button:a]` when using a controller. this has been fixed, and they now display an appropriate sprite.

add controller support to Ball Jump button prompts

---

scripts/objects/world/DarkPartyMenu.lua

* Randomizer max now uses `Game:getFlag("party_max")` instead of 4
* Removed the in party updates, as FireRainV said it'll happen automatically

Updates to the randomizer

---

scripts/world/cutscenes/room1.lua

Fixed a bug that got Susie stuck in collision after the blanket cutscene (Only happened when she was the party leader)

Update to Room 1, Fixed Susie Softlock in Wall

---

libraries/CharacterKeyItems/scripts/objects/LancerGotchi.lua

The bug was that the animation would reset every 3 seconds, causing a visual issue.

Small fix for the Lancer key item

---

libraries/magical-glass/lib.lua
mod.lua

Old saves were missing light world magic stats. That's all there was to it.

Fix LightStatMenu crashing with old save files

---

scripts/objects/world/DarkPartyMenu.lua

When using the party menu in the light world, any spawned followers will now use the appropriate light actor.

Added Light checks to party menu

---

scripts/main/utils_lore.lua

Use this for quests and such where you're temporarily not allowed to use a party member

Mod:lockPartyMember(id)

---

scripts/hooks/DarkConfigMenu.lua

Optimised the system to prevent crash from happening when Kristal tries to show a custom key bind that don't have a "gamepad"  variable at all.
Fixed a minor glitch due to the anti crash system where the gamepad bindings would reset upon reopening the menu if those didn't have a "gamepad" var by default.
(Also took out a print that were just for my testing)

Fix for XtraControl

---

scripts/main/utils_general.lua
scripts/world/cutscenes/pc.lua

1. We never added the source code version for a changed Kristal identity.
2. Added detection for Kristal save files other than file_0 through file_3.

Fix save detection for Kristal mods

---

libraries/TauntSoul/scripts/objects/TauntSoul.lua
scripts/data/items/armors/focus.lua
scripts/globals/Gangnam.lua
scripts/globals/Speen.lua
scripts/hooks/Soul.lua

Some key binds where sort of hard coded such as the speen, focus, gangnam style.
I also modified the focus item so that the desc change based of your key bind set for the focus button.
Also made the taunt button parry in battle, which shouldn't mess with anything.
Normally everything should work and I shouldn't have touching anything that I wasn't suppose too (in term of the modification that I was doing).

Un-Harcode your key binds

---

scripts/hooks/DarkConfigMenu.lua

Fixed an issue where, in the config menu, pressing cancel in the "controls" state would close said menu instead of sending you to its "main" state.

Fix Lib Xtra Config

---

libraries/ExtraControl/lib.json
mod.json
scripts/hooks/DarkConfigMenu.lua

Added the fact that the key binds are saved once they're change.
Also added a gamepad var for the key bind that were missing one so that they're saved properly when changed in the control menu.

Updated Xtra Control (QoL)

---

mod.lua
scripts/world/cutscenes/_main.lua
scripts/world/cutscenes/hometown.lua
scripts/world/cutscenes/jaru_walkie_talkie.lua

- Skipping the main intro will still ask the player if they want to activate the post-snowgrave content if they have a file for it
- To skip the intro, you'll actually have to press C and D, instead of the menu key and D _(yeah I did this instead of making the text adapt to which key is the menu key)_
- Made some dialogues less "Kris-only" in Hometown
- Added a list of rooms in which JARU's talkie walkie will have its signal jammed, like in MB's room

Changes to Intro cutscene + Hometown dialogues + jammed talkie walkie

---

libraries/magical-glass/lib.lua

Prevents the game from crashing every time a textbox finishes.
Shoutouts to VSCode for not giving me any indication that I changed 6000 line endings

Workaround MG breaking minifaces
