darkplace-dr/Dark-Place

- README.md
- libraries/MoreBattle/lib.json
- libraries/MoreBattle/lib.lua
just in case yall want more than 3 party members lmfao have fun
> Morebattle by Cоrе#2611 on Kristal discord (The GOAT)

- scripts/data/items/key/cell_phone.lua
- scripts/data/items/mediumpizza.lua
- scripts/world/Dark-Place.world
- scripts/world/maps/room3/data.lua
- scripts/world/maps/room3/room3.tmx
- Fixed a bug with the Cell Phone where the `mcdonalds` easter egg would be completely overwritten by the `bbqbb` easter egg.
- Tweaked room3 to include the Trash Rudinn NPC cause I forgot to add it to the map apparently, lol.
- Added a Medium Pizza item.
- Added a world file for the mod, which I think will be pretty convenient for map making.
> Just some bug fixes and some other stuff.

- scripts/world/cutscenes/room3.lua
Accidentally deleted it when I made the last pull request.
> Added back in Pizza Tower cutscene in room3, lol.

- .gitignore
- scripts/hooks/Fader.lua
- scripts/world/events/whitedoor.lua
also re-structured the white door cutscene a bit because repetitive code :(
> make white door fade accurate to omori

- scripts/world/events/elevator_input.lua
> Fix elevator

- mod.lua
- scripts/data/actors/balloondog.lua
- scripts/data/actors/doobie.lua
- scripts/data/actors/magolor.lua
- scripts/data/actors/morshu.lua
- scripts/world/cutscenes/room3.lua
- scripts/world/maps/room3/map.lua
> Make anim slower in morshu if Simplify VFX is on

- mod.lua
Pain
This is why you don't make  unrelated changes
> Fix room3 ach

- scripts/hooks/GameOver.lua
> fucking print line

- scripts/world/maps/devroom/data.lua
- scripts/world/maps/devroom/devroom.tmx
Readded Velvet NPC cause she was accidentally removed and added map transition for Party Room.
> Fixed up Dev Room map.

- scripts/world/cutscenes/room1.lua
> Fix camera in React_To_YOU cutscene

- libraries/KristalAchievements/lib.lua
- libraries/KristalAchievements/scripts/objects/world/AchievementsMenu.lua
- scripts/battle/cutscenes/dummy.lua
- scripts/world/cutscenes/desslmao.lua
- scripts/world/cutscenes/room1.lua
- scripts/world/cutscenes/room3.lua
- scripts/world/events/squeak.lua
May not correlate with whatever the last person that modified that library wanted to do, but now it shouldn't crash anymore
> Fix crashes with achievements

- libraries/MoreParty/lib.lua
Just updating one of the libraries, lol.
> Updated MoreParty library to latest version.

- scripts/world/tilesets/objects.lua
- scripts/world/tilesets/objects.tsx
opening mod crashed cuz the objects tileset couldnt get 3 images. fixed that
> fixed stupid bug

- mod.lua
Fixed a small bug with the taunting mechanic where the player would be allowed to taunt during a cutscene.
> Taunting mechanic bug fix.

- README.md
Man, we really need a permanent invite or something, lmao.
> Fix Discord Invite again.

- README.md
Special thanks to HUECYCLES and Simbel for letting me know about this feature on Discord, lol. The invite in the description should be permanent now. (Hopefully I won't have to change it again, lol.)
> Okay so apparently making a permanent invite is pretty easy.

- libraries/nametags/scripts/hooks/WorldCutscene.lua
- scripts/jukebox_songs.lua
Added the Oregano Desert secret theme so you can strike taunts in sync!
and fixed the nametag stuff
> Now you too can Strike a Taunt like Peppino

- scripts/world/cutscenes/room1.lua
> Added 4 (*6) surnames for the party members

- scripts/world/maps/warphub/data.lua
- scripts/world/maps/warphub/warphub.tmx
New Stuff!
- Added ads for new codes used for the warpbin
- New sold property! It's Pasta Time! (when it opens...)
> Minor Warphub Update

- mod.json
- mod.lua
- Added "YOU", "KRIS" and "MERG"
- Naming yourself "MERG" triggers a No-Hit Mode of sorts for the mod. (Special thanks to FireRainV for the idea and no-hit code!)
> New name easter eggs.

- mod.json
Updates the preview to include the proper hash for it's recent version. (also my github finally works lets fucking go) (I learnt i think idfk)
> Update mod.json to include hash ID

- scripts/world/maps/devhotel/devhotel_lobby.lua
- scripts/world/maps/devhotel/devhotel_lobby.tmx
I forgot the devhotel lobby, that the only thing lmao
> Small addition to The patch: of all time

- scripts/globals/BORDER_TYPES.lua
- scripts/hooks/DarkConfigMenu.lua
- scripts/main/utils_general.lua
Obsoletes BrandonK7200:Border-toggle-WIP basically, the devhotel stuff should be a part of main anyway
I planned to let devs add new options but I have to figure out how to deal with a problem first
> DCM border setting attempt

- libraries/JukeboxMenu/scripts/objects/world/JukeboxMenu.lua
- libraries/KristalAchievements/lib.lua
- libraries/KristalAchievements/scripts/objects/Achievement.lua
- libraries/LevelingSystem/scripts/hooks/Battle.lua
- libraries/LevelingSystem/scripts/hooks/EnemyBattler.lua
- libraries/LevelingSystem/scripts/hooks/PartyMember.lua
- libraries/LevelingSystem/scripts/hooks/world/DarkPowerMenu.lua
- libraries/Light World Stats/scripts/hooks/LightEquipItem.lua
- libraries/Light World Stats/scripts/hooks/LightStatMenu.lua
- libraries/UNDERTALE Save Point/scripts/hooks/Savepoint.lua
- libraries/Ultimate RIBBIT/scripts/hooks/DarkMenuPartySelect.lua
- libraries/elevators/scripts/hooks/Map.lua
- libraries/musiclogos/scripts/objects/musiclogo.lua
- libraries/nametags/scripts/hooks/WorldCutscene.lua
- libraries/nametags/scripts/objects/Nametag.lua
- scripts/battle/encounters/susie_noyno.lua
- scripts/hooks/Actor.lua
- scripts/hooks/DarkConfigMenu.lua
- scripts/hooks/DarkFountain.lua
- scripts/hooks/DialogueText.lua
- scripts/hooks/EnemyBattler.lua
- scripts/hooks/Fader.lua
- scripts/hooks/GameOver.lua
- scripts/hooks/Map.lua
- scripts/hooks/Soul.lua
- scripts/hooks/Textbox.lua
- scripts/hooks/World.lua
- scripts/hooks/encounter.lua
- scripts/world/cutscenes/chapter1.lua
- scripts/world/maps/field/map.lua
Figured I could do this instead of doing
the ach_def thing
> Add class annon to some files etc.

- scripts/hooks/World.lua
- scripts/world/maps/​/map.lua
- scripts/world/scripts/​.lua
Reduced probability of it happening
Added a timer for MB to attack if the player takes too long
> Changes to the weird event

- scripts/world/cutscenes/everhall.lua
I'm allowed to do this, man. The Everhall is mine. Also, it was recently reduced in size so I decided to increase it a hundredfold. You're welcome, Anon273.
> Expanded the Everhall from 100 to 10k

- libraries/blue_soul_library/scripts/objects/BlueSoul.lua
- scripts/battle/encounters/googledino.lua
- scripts/battle/enemies/googledino.lua
- scripts/world/maps/googlefield/data.lua
- scripts/world/maps/googlefield/googlefield.tmx
Made the cutscene only play once. As well as making it slightly harder by changing the blue soul up.
> Small GoogleDino changes

- scripts/world/cutscenes/devhotel_room_003.lua
The quest line is in my dev hotel room.
> First quest line

- libraries/Questline/lib.lua
because Jaru broke stuff again
> Fix quest adding

- scripts/main/live_bulborb_reaction.lua
> Make v0.8.0 not bail when running the mod because of Bulborb

- libraries/badges/lib.json
- libraries/badges/lib.lua
Now badges do nothing at all in LW
This is **TEMPORARY** behavior basically implemented in order to make LW rooms work, until @NyakoFox gets back to this
> Make badges junk for now

- scripts/world/cutscenes/cssusie.lua
- scripts/world/cutscenes/cybercity.lua
- scripts/world/cutscenes/darkcade_f1.lua
- scripts/world/cutscenes/desslmao.lua
- scripts/world/cutscenes/floor2.lua
- scripts/world/cutscenes/lounge.lua
- scripts/world/cutscenes/room4.lua
- scripts/world/cutscenes/spamgolor.lua
- scripts/world/cutscenes/spamroom.lua
I don't remember what all of these were edited, but all of them are in there
> Add Jamm to some cutscenes

- scripts/world/cutscenes/devroom.lua
- scripts/world/cutscenes/spamroom.lua
- scripts/world/maps/cybercity/joint_shop_alley.lua
- scripts/world/maps/cybercity/joint_shop_alley.tmx
What's new?
- Click & Button Shop exterior
- Velvet new dialogue if Susie is not in the party
- V!Spam cutscene tweaks
> A Minor Udpate ig

- scripts/data/items/key/sfb_key.lua
- scripts/hooks/GameOver.lua
- scripts/main/utils_general.lua
- scripts/shops/jeku_shop.lua
- scripts/world/cutscenes/devroom.lua
- Jeku has new dialogues if skipping his game over sequence
- Added `Mod:getPartyLove()`
- The Blue Key's price is affected by the party's LOVE now (and Jeku doesn't mention anything about it)
- Dialogue fix. Wow.
> Jeku related changes

- scripts/battle/enemies/chevelour.lua
- scripts/battle/waves/chevelour/charge.lua
What's new?
- Chev's charge attack fixed
- Chev Insult nerf
> Chevelour Battle Update (1/2)

- scripts/ach/blankiequest.lua
> Made Blankie Quest Title Funny

- mod.lua
- scripts/objects/world/DarkPartyMenu.lua
- scripts/world/cutscenes/room1.lua
> Reworked Wardrobe, Allowing to customize the maximum amount of party members

- scripts/objects/world/DogCheck.lua
https://github.com/BrandonK7200/Dark-Place/assets/87152256/b02bf454-d29b-40df-ba9d-ce8eabbd86de
> Improved Summer Dogcheck

- mod.lua
The console will now state all possible reasons why it detected a save file as old
> Clearer explanations as to why a save file is detected as old

- libraries/elevators/scripts/world/events/elevatorbuttons.lua
- scripts/objects/world/IncMenu.lua
Elevators can support more than 4 floors now as a result
> reworked elevator floor selection

- libraries/elevators/scripts/world/events/elevatorbuttons.lua
- scripts/objects/world/IncMenu.lua
"elevatormode" displays the floor name instead of a number.
> Add "elevatormode" to IncMenu

- scripts/data/items/badges/easy_flee.lua
- scripts/hooks/encounter.lua
Allows for an easier escape from battles.
> Easy Flee badge

- scripts/main/debugsystem.lua
> Minigames debug

- scripts/battle/waves/unavoidable_ania.lua
As in it goes through Chaos Emeralds and parries now. It's supposed to be unavoidable; I'm making it that way.
> Shade Ania's unavoidable attack is definite

- scripts/world/maps/cybercity/alleyzero/alleyzero.tmx
- scripts/world/maps/cybercity/alleyzero/data.lua
- scripts/world/maps/cybercity/alleyzero/map.lua
Also added a reward chest at the end of the alley he's in, containing a BP Plus
> Fixed Zero persisting after defeating him

- scripts/main/battle_taunt.lua
> optimized the taunt optimizations

- scripts/battle/enemies/zero.lua
> Disable debug act in the zero fight

- libraries/Ultimate RIBBIT/scripts/data/items/items/postcard.lua
- libraries/Ultimate RIBBIT/scripts/data/items/items/punchcard.lua
- scripts/data/items/gemapple.lua
- scripts/jukebox_songs.lua
Postcard, Punch Card and Gem Apple no longer trigger refund.
> Patch infinite money glitch 2023

- mod.lua
from the window utils library I'm working on
> Forgot to remove this

- scripts/battle/encounters/ania_boss.lua
- scripts/battle/encounters/big_booty.lua
> Flee fix for a couple fights

- mod.lua
And there's nothing you can do
> I'm stealing PR 500

- scripts/data/items/badges/l_emblem.lua
- scripts/data/items/badges/w_emblem.lua
A bug where you could be purple without equipping both badges
> Fixed the Waluigi Bug

- mod.lua
- scripts/hooks/World.lua
- scripts/world/cutscenes/devroom.lua
- scripts/world/maps/​/.tmx
- scripts/world/maps/​/data.lua
- scripts/world/maps/​/map.lua
- scripts/world/scripts/​.lua
- Replaced Utils.random() by love.math.random(). _So that people can actually get the event_
- MB can now catch up to you if Kris has the Pizza Toque equipped
- Added the prefix "mb_" to every flag used for MB's event
- Fix crash caused by the script file not being recognized as a lua file anymore...?
- Renamed _GB sidequest... again.
> Fix MB event

- mod.lua
- scripts/objects/GonerBackgroundPiece.lua
- scripts/world/cutscenes/room1.lua
- scripts/world/maps/room1/data.lua
- scripts/world/maps/room1/map.lua
- scripts/world/maps/room1/room1.tmx
@JustAnotherRandomGithubUser You didn't set a condition for the interactable that starts `room1.spooky`
> Fix "Able talk to Skid and Pump anytime other than October and doing so crashes the game"

- scripts/objects/WiiSaveMenu.lua
This is just in here so when the Wii BIOS mod is released, you can save your progress in the Wii slot. You will not be using it at this point, it's 100% for the Wii BIOS mod.
> Wii Save Menu

- libraries/magical-glass/lib.lua
- scripts/data/party/frisk.lua
fixed running bug and changed frisks items to the magical glass versions
> fixed running bug and changed frisks items to the magical glass versions

- scripts/battle/enemies/big_arms.lua
- scripts/battle/enemies/eggman.lua
- scripts/battle/waves/egg2_fly.lua
I didn't realize there'd be a True Arena of sorts for this. Now I realize and set the Standard X-Act. Only Jamm and Mario get special abilities with this, though. Chess Battle Advanced.
> Eggman Updates

- scripts/data/items/badges/rgb_noelle.lua
Makes Noelle stronger and RGB!
Currently unobtainable.
> Added "Snow Angel" badge

- scripts/main/utils_general.lua
- scripts/shops/jeku_shop.lua
I'm sure you would never guess why it didn't work on Linux
> Backslash Backslash Backslash Backslash Backslash Backslash

- mod.lua
- scripts/main/utils_general.lua
- scripts/world/cutscenes/pc.lua
> Added name option to gifts data

- mod.lua
- scripts/world/cutscenes/pc.lua
Turns out the last PR was not the last
> Allow to check multiple files for gifts

- scripts/world/cutscenes/fountain1.lua
> Fix fountain1 assuming Susie's presence (-> v1.x)

- mod.lua
- scripts/minigames/ball_jump/level_1.lua
- scripts/objects/minigame/BallJump/BallJump.lua
- scripts/objects/minigame/BallJump/BallJumpBackChuck.lua
- scripts/objects/minigame/BallJump/BallJumpBall.lua
- scripts/objects/minigame/BallJump/BallJumpBullet.lua
- scripts/objects/minigame/BallJump/BallJumpChuck.lua
- scripts/objects/minigame/BallJump/BallJumpEntity.lua
- scripts/objects/minigame/BallJump/BallJumpFakeBall.lua
- scripts/objects/minigame/BallJump/BallJumpFastBall.lua
- scripts/objects/minigame/BallJump/BallJumpFinish.lua
- scripts/objects/minigame/BallJump/BallJumpGoomba.lua
- scripts/objects/minigame/BallJump/BallJumpPlayer.lua
- scripts/objects/minigame/BallJump/BallJumpSCoin.lua
- scripts/objects/minigame/BallJump/BallJumpSpikeF.lua
- scripts/objects/minigame/BallJump/BallJumpSpiny.lua
- Entities now has a shared parent class `BallJumpEntity` to unify the collision, moving 'n' stuff
- Entities now move after checking collision
- Levels now can use HUMP timer script for patterns
- "Press [confirm] to jump" fades out after 4 secs
> mini/BallJump: Misc refactors and changes

- preview/wii_preview.lua
This update for Wii BIOS isn't out yet so bear with me
> Added maintenance mode icon look

- scripts/data/party/kris.lua
- scripts/data/party/susie.lua
> Fix oversight in #623

- mod.lua
- scripts/hooks/GameOver.lua
the funny title code is now a function.
> Mod:funnytitle()

- mod.lua
- scripts/hooks/World.lua
- scripts/world/maps/​/map.lua
- You can now be free from spooky goo thing at some places
- Followers can't follow you any more in your impending doom
> Fix some MB issues

- libraries/miss_pauling/scripts/data/items/weapons/derringer.lua
- scripts/data/items/light/band_sling.lua
- scripts/data/items/light/chain_sling.lua
- scripts/data/items/light/dsi.lua
- scripts/data/items/light/gamecube_controller.lua
- scripts/data/items/light/old_mallet.lua
- scripts/data/items/light/pellet_gun.lua
- scripts/data/items/light/rb_gun.lua
- scripts/data/items/light/rope_sling.lua
- scripts/data/items/light/whip_sling.lua
- scripts/data/items/weapons/basic_hammer.lua
- scripts/data/items/weapons/basic_sling.lua
- scripts/data/items/weapons/bigsling.lua
- scripts/data/items/weapons/ds_hammer.lua
- scripts/data/items/weapons/hornet_gun.lua
- scripts/data/items/weapons/oblitersling.lua
- scripts/data/items/weapons/simpsling.lua
- scripts/data/items/weapons/wiimote.lua
They don't seem to convert to said light counterparts. If anyone knows what the issue is, let me know.
> Light counterparts for my weapons

- scripts/data/party/alseri.lua
- scripts/data/party/asriel.lua
- scripts/data/party/berdly.lua
- scripts/data/party/bor.lua
- scripts/data/party/brandon.lua
- scripts/data/party/dess.lua
- scripts/data/party/dumbie.lua
- scripts/data/party/frisk2.lua
- scripts/data/party/jamm.lua
- scripts/data/party/mario.lua
- scripts/data/party/noel.lua
- scripts/data/party/noelle.lua
- scripts/data/party/noyno.lua
- scripts/data/party/osw.lua
- scripts/data/party/ralsei.lua
- scripts/data/party/robo_susie.lua
- scripts/data/party/sam.lua
- scripts/data/party/susie.lua
- scripts/data/party/synthlave.lua
For every party member who has a face sprite, they were added to the light world menu
> Adding faces to light world menu

- scripts/world/maps/floor2/doors_right/data.lua
- scripts/world/maps/floor2/doors_right/doors_right.tmx
- scripts/world/maps/floor2/hell.lua
- scripts/world/maps/floor2/hell.tmx
finally, the room ran at 15 FPS.
Also, you can now exit it without debug.
> Removed some enemies and added an exit to the HELL map

- libraries/MoreParty/lib.json
- libraries/MoreParty/lib.lua
- libraries/magical-glass/lib.lua
- libraries/magical-glass/scripts/lightbattle.lua
- libraries/magical-glass/scripts/lightbattle/lightencounter.lua
- libraries/magical-glass/scripts/lightbattle/lightenemybattler.lua
- libraries/magical-glass/scripts/lightbattle/ui/lightactionbox.lua
- libraries/magical-glass/scripts/lightbattle/ui/lightbattleui.lua
- libraries/magical-glass/scripts/objects/underplayer.lua
Magical-Glass and MoreParty update
> Updated MG and MP

- libraries/Questline/lib.json
- libraries/Questline/lib.lua
Dark Place will now require Kristal commit `fbe57ae` or above for this update.
> Updated Questline

- scripts/shops/jeku_shop.lua
Don't even look at `jeku_shop.lua` anymore. It's not worth it. You have a life ahead that deserves to be seen with eyes not destroyed by whatever the fuck I wrote in this file
Anyway Jeku isn't affected by shatter anymore and even has a reaction to it. All for the sake of meta silly guy being very meta
> Local meta silly guy became even more meta at the cost of my sanity

- README.md
- scripts/jukebox_songs.lua
Updated images due to Discord's CDN update a few months ago and made the instructions more general so players won't mistakenly think 0.8.1 is the only version capable of running Dark Place (and so I won't have to update it every release)
Also added and changed some credits
> Updated installation instructions & added some credits

- scripts/shops/jeku_shop.lua
> Fix crash if Shatter was never installed

- scripts/battle/lightenemies/arch_monk.lua
- scripts/battle/lightenemies/froglin.lua
- scripts/battle/lightenemies/python.lua
- scripts/battle/lightenemies/rodenteer.lua
- scripts/battle/lightenemies/spidron.lua
- scripts/battle/lightenemies/waspon.lua
- scripts/data/items/light/gamecube_controller.lua
For the Deoxynn enemies, I did not add the attacks. I added the acts (except for Arch Monk, since I didn't know how throw acts are gonna work) and other text from Deoxynn, plus added some new check text. I also adjusted the stats so you can't just instakill all of these with a 3-member party.
> GC Controller fix and Deoxynn enemy update

- scripts/main/utils_general.lua
- scripts/world/cutscenes/pc.lua
> utils_general, pc: Swap hasSaveFiles 2nd and 3rd param, that didn't make sense

- libraries/ExtraControl/lib.json
- libraries/ExtraControl/lib.lua
- scripts/hooks/DarkConfigMenu.lua
Imported XtraCtrl lib, normally everything should work fine.
> XtraControl Import

- scripts/world/cutscenes/room1.lua
> i think i accidently removed the wall cutscene

- scripts/hooks/Player.lua
Jamm forgot to remove the afterimage sprites after they go invisible
added my shader (only shows if you have simplify vfx off)
> starman update

- mod.lua
- scripts/world/cutscenes/flowey_check.lua
> mod.lua: Check for KRISTAL_EVENT table presence

- scripts/battle/cutscenes/sneo_rematch.lua
- scripts/battle/enemies/booty.lua
- scripts/battle/enemies/dummy.lua
- scripts/battle/enemies/eggman.lua
- scripts/battle/enemies/error.lua
- scripts/battle/enemies/googledino.lua
- scripts/battle/enemies/gunman.lua
- scripts/battle/enemies/poseur.lua
- scripts/battle/enemies/zero.lua
- scripts/battle/lightenemies/ceroba_geno.lua
- scripts/battle/lightenemies/goosic.lua
- scripts/battle/lightenemies/jandroid.lua
For the most part, the ACT stuff is to make sure the text says "Jamm and Marcy" or some variant (or even just one of them individually), rather than "J+M".
> J+M battle stuff

- libraries/saddiamondman's unorganised folder/scripts/data/actors/bepis_master.lua
- libraries/saddiamondman's unorganised folder/scripts/world/cutscenes/master.lua
- scripts/world/maps/tutor_room/map.lua
Gone are the days of walking into the tutorial room with all your favorite characters in your party only to be greeted with an error screen!
Currently uses Test Master's sprite.
> "Bepis Master" for tutorial room

- mod.lua
- scripts/data/items/badges/tension_plus.lua
- scripts/shops/diamond_store.lua
Draft because there's currently no way to obtain it aside from debug menu, and I'm not sure how balanced this is. Also, there's a new function in the `mod.lua`...
Update: Both of these have been somewhat solved.
> Add Tension Plus badge

- scripts/cards/cards/pot_of_greed.lua
- scripts/objects/cards/Card.lua
fixed the back of pot of greed not showing
> back card fix

- libraries/KristalAchievements/lib.lua
- libraries/LocalLuaDebuggerIntergration/lib.lua
- libraries/WeatherLib/lib.lua
- libraries/badges/lib.lua
- libraries/books/lib.lua
- libraries/borders/lib.lua
- libraries/deltacrack/lib.lua
- libraries/music2/scripts/hooks/Music.lua
- scripts/main/minigames_glue.lua
Doesn't improve memory leak situation though
> dark_place: Attempt to reduce leftovers after exiting

- scripts/objects/world/events/SavePoint.lua
- scripts/world/maps/darkcade/outside/data.lua
- scripts/world/maps/darkcade/outside/outside.tmx
- scripts/world/maps/room3/data.lua
- scripts/world/maps/room3/room3.tmx
Also added the map name in Dark-cade and moved Doobie closer to the corner of the room
> Fix SavePoint's weird message not updating when changing party

- scripts/ach_order.lua
If I had a nickel for each error that occurred because I forgot to delete one line, I'd have at least a few nickels
> Fixing missing achivements Attempt #1

- scripts/world/cutscenes/desslmao.lua
Fixed a crash where noel talks to Brenda while doing math
> Noel fucking did it agian
